version: '3.8'
services:
  frontend:
    build: ./app/frontend
    ports:
      - "3000:3000"
    networks:
      - app_net

  backend:
    build: ./app/backend
    ports:
      - "5000:5000"
    networks:
      - app_net

  nginx:
    image: nginx
    volumes:
      - /nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app_net

  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - app_net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_net

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - app_net

networks:
  app_net:

volumes:
  jenkins_home:
    